credentials:
  usernames:
    ProductSupport:
      email: productsupport@example.com
      name: Product Support
      password: $2b$12$A8aX5Hy0Xz3Iu5xXGXGz8OeL1GK3NVsXWJJjZE7jTxIdQqsfM5m2e  # Hashed password for "Alog2024!"
cookie:
  expiry_days: 30
  key: random_signature_key_change_this
  name: analogic_auth_cookie
preauthorized:
  emails:
  - melsby@example.com
