credentials:
  usernames:
    ProductSupport:
      email: productsupport@example.com
      name: Product Support
      password: Alog2024! # To be replaced with a hashed password
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@example.com
